### ISSUE TITLE
이번에 바뀐 운영탭에 대응하지 못하여 에러가 발생합니다

### ISSUE THREAD

**Issue by cclue06** [tjgus1668/ArcaliveCrawler#3]
System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: Arcalive.ArcaliveCrawler.CrawlBoards(Nullable`1 From, Nullable`1 To, Int32 startPage) 파일 C:\Users\tjgus\source\repos\Arcalive\Arcalive\Arcalive\ArcaliveCrawler.cs:줄 77
   위치: ArcaliveForm.Form1.<>c__DisplayClass10_0.<button1_ClickAsync>b__0() 파일 C:\Users\tjgus\source\repos\Arcalive\ArcaliveForm\Form1.cs:줄 118
   위치: System.Threading.Tasks.Task.InnerInvoke()
   위치: System.Threading.Tasks.Task.Execute()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: ArcaliveForm.Form1.<button1_ClickAsync>d__10.MoveNext() 파일 C:\Users\tjgus\source\repos\Arcalive\ArcaliveForm\Form1.cs:줄 121
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   
   이전 버전에서도 이러네요..

+) 이번에 바뀐 (권한 없음) 으로 뜨는 운영탭이 문제를 일으키는거 같습니다..

**Comment by cclue06** [comment]
아마 이번에 바뀐 운영탭 때문에 그런거 같습니다 감사합니다

**Comment by tjgus1668** [comment]
1.0.7760.30198 버전에서 수정되었습니다
